projet_platform:
    resource: "@PROJETPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

projet_core:
    resource: "@PROJETCoreBundle/Resources/config/routing.yml"
    prefix:   /
