projet_platform_home:
    path:      /{id}
    defaults:
        _controller: PROJETPlatformBundle:Ticket:index
        id:        1
    requirements:
        id: \d+

projet_platform_add:
    path:      /add/{fn}
    defaults:
        _controller: PROJETPlatformBundle:Ticket:add
        fn:        1
    requirements:
        fn: \d+

projet_platform_del:
    path:      /del/{id}
    defaults:
        _controller: PROJETPlatformBundle:Ticket:del
        id:        1
    requirements:
        id: \d+

projet_platform_billing:
    path:      /bill/{id}
    defaults:
        _controller: PROJETPlatformBundle:Ticket:billing
    requirements:
        id: \d+