services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    PROJET\PlatformBundle\:
        resource: '../../*'
        exclude:  '../../{Entity,Tests,Repository}'

    PROJET\PlatformBundle\Count\Check:
        public: true

    PROJET\PlatformBundle\Count\Count:
        public: true

    PROJET\PlatformBundle\Billing\Billing:
        public: true

    PROJET\PlatformBundle\SubmitForm\SubmitForm:
        public: true