services:
    projet_platform.price:
        class: PROJET\PlatformBundle\Price\Price

    projet_platform.count:
        class: PROJET\PlatformBundle\Count\Count

    projet_platform.check:
        class: PROJET\PlatformBundle\Count\Check

    projet_platform.submitForm:
        class: PROJET\PlatformBundle\SubmitForm\SubmitForm
        arguments:
          - "@projet_platform.price"
          - "@projet_platform.count"
